version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: nicolas  
      MYSQL_DATABASE: cellPhonesCompany
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Aquí estamos refiriéndonos al volumen 'mysql-data'
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-server
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=nicolas
      - MYSQL_DATABASE=cellPhonesCompany
    ports:
      - "3333:3333"
    depends_on:
      - db
    restart: always

volumes:
  mysql-data:  # Aquí definimos el volumen 'mysql-data'
    driver: local
