### Para filter db
GET http://localhost:3333/db

### para filter por Id
GET http://localhost:3333/db?id=1

### para filter por name
GET http://localhost:3333/db?name=samsung%20galaxy%20s23

### para filter por brand
GET http://localhost:3333/db?brand=samsung

### para filter por category
GET http://localhost:3333/db?category=smartfone